#path to repo
#repo_path: HVAC_Control_DRL/

#data file path
data_file_path: data/1ZoneDataCenterHVAC.csv
result_path: results/

pickle_path_result: results/pickles/
data_result_path: data/figures/
labels_path: video_labels/


random_output: False

# simulation data control paramters
log_output: True  # activate logging results. Disable to speed up training process 
print_output_single: False # print out every single measurement even if not done  
print_output_all: False   # print out all output (only when episode is done)    
save_output: False  # save individual measurements to output file
output_file: results/output/outputTemp.txt # output file for chanes in output temp for all episodes (save only )


TOUT1_target: 22   # Temp target for Zone 1

#Model variables
no_inputs: 5
no_outputs: 2

#model
#both of the below are in the results folder
pickle_path: pickles/
model_result_path: model/figures/


# DDPG settings
training_steps: 30000
test_episodes: 1


# Regression variables: 
#reg_model: ridge #either linreg or ridge for L2 regularization
reg_model: linreg
alpha: 0.5 #alpha for Ridge
norm_mode: max #either full or max: full is 0-1, max scales to the max


# Min and max degree of polynomials features to consider
degree_min: 2
degree_max: 2
# Test/train split
test_set_fraction: .2

# RL Variables:

# Environment variables: 
scale_var: 10.0 # scales all the normalized input/output values

# The fraction within range of the target within which we say the agent has reached the goal.

thresh1: .003 #within 4% of the target
thresh2: .003
thresh3: .003


# Reward upon reaching the goal
# This is multiplied by scale_var
reward: 1000

# Scaling variable for the MSE:
MSE_scale: 10 #multiply the MSE by this to get negative reward

# Action range: can go up or down this % of the range
action_range: 2
max_in_change: 2 # maximum input change
rate_change: .05 # MVP model
max_PUE: 3
min_PUE: 1
max_TZ: 35
min_TZ: 8
min_Tin: 5
max_Tin: 30
min_ITU_scaled: 1 
max_ITU_scaled: 1.5



# Noise is really an add-on to the regression model: it adds some random noise to
# the deterministic regression output to more closely mimic the simulation space
# Noise is a fraction of the threshold for accuracy: a fraction of thresh1
noise: .05


# Experiment variables:


# Rendering settings that may need to be tweaked per model:
buff_axis: 0.2 #buffer for top & bottom of screen 
scalestep: 50 #number steps for step axis

#plot variables:
#video:

ftype: .png
labels:
  - G1F
  - G1T
  - G2F
  - G2T
  - O1
  - O2
  - O3

#3d data plot columns:
xvar: 1
yvar: 2
zvar: 0



fs: 14 #fontsize for x & y labels

#Data variables


#data management variables: 

#variables to change the scale for:
change_scale:
  - ITUZ1
  - ITUZ2

#naming (5 input file)

in_var:
  - TDXZ1
  - TDECZ1
  - TIECZ1
  - TOUT
  - ITUZ1

# 
#naming (6 input file)
in_var:
#  - TDXZ1
#  - TDECZ1
#  - TIECZ1
#  - TDXZ2
#  - TDECZ2
#  - TIECZ1
#  - TOUT
#  - ITUZ1
#  - ITUZ2 

out_var:
  - PUE
  - TZ1

all_var:
  - Date/Time
  - TOUT
  - ITUZ1
  - ITUZ2
  - PUE
  - TZ1
  - TZ2
  - TDXZ1
  - TDECZ1
  - TIECZ1
  - TDXZ2
  - TDECZ2
  - TIECZ2


#corresponding names, for figure labeling: (4 input parameter)

in_var_name:
  - TDXZ1
  - TDECZ1
  - TIECZ1
  - TOUT
  - ITUZ1

#corresponding names, for figure labeling: (4 input parameter)
#in_var_name:
#  - TDXZ1
#  - TDECZ1
#  - TIECZ1
#  - TDXZ2
#  - TDECZ2
#  - TIECZ2
#  - TOUT
#  - ITUZ1
#  - ITUZ2

out_var_name:
  - PUE
  - TZ1
